# Generated by Django 4.1.13 on 2026-06-10

import django.core.validators
from django.db import migrations, models
import users.avatar_service


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=50)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("direct", "Direct"),
                            ("group", "Group"),
                        ],
                        db_index=True,
                        default="private",
                        max_length=10,
                    ),
                ),
                ("direct_pair_key", models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ("description", models.TextField(blank=True, default="", max_length=2000)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to=users.avatar_service.group_avatar_upload_to)),
                ("avatar_crop_x", models.FloatField(blank=True, null=True)),
                ("avatar_crop_y", models.FloatField(blank=True, null=True)),
                ("avatar_crop_width", models.FloatField(blank=True, null=True)),
                ("avatar_crop_height", models.FloatField(blank=True, null=True)),
                (
                    "is_public",
                    models.BooleanField(default=False, help_text="Public groups are discoverable and joinable without invite."),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Negative 10-digit public fallback id for groups.",
                        max_length=11,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="public_id must be a negative 10-digit numeric value.",
                                regex="^-[1-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "slow_mode_seconds",
                    models.PositiveIntegerField(default=0, help_text="Minimum delay between messages per member (0=off)."),
                ),
                (
                    "join_approval_required",
                    models.BooleanField(default=False, help_text="Require admin approval for join requests."),
                ),
                ("max_members", models.PositiveIntegerField(default=200000)),
                ("member_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "chat_room",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "public")),
                        fields=("kind",),
                        name="room_single_public_kind_uniq",
                    ),
                ],
            },
        ),
    ]
