# Generated by Django 4.1.13 on 2026-06-10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import messages.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(db_index=True, max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="rooms.room",
                    ),
                ),
                ("message_content", models.TextField()),
                ("date_added", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("profile_pic", models.CharField(blank=True, max_length=255, null=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("original_content", models.TextField(blank=True, default="")),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="chat_messages.message",
                    ),
                ),
            ],
            options={
                "db_table": "chat_message",
                "ordering": ("date_added",),
                "indexes": [
                    models.Index(fields=["room", "date_added"], name="msg_room_date_idx"),
                    models.Index(fields=["username", "date_added"], name="msg_user_date_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="chat_messages.message",
                    ),
                ),
                ("file", models.FileField(upload_to="chat_attachments/%Y/%m/")),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("file_size", models.PositiveBigIntegerField()),
                ("thumbnail", models.ImageField(blank=True, null=True, upload_to="chat_thumbnails/%Y/%m/")),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "messages_attachment",
                "ordering": ["uploaded_at"],
                "indexes": [
                    models.Index(fields=["message"], name="attachment_message_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageAttachmentUpload",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachment_uploads",
                        to="rooms.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_attachment_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("file_size", models.PositiveBigIntegerField()),
                ("received_bytes", models.PositiveBigIntegerField(default=0)),
                ("storage_name", models.CharField(max_length=500, unique=True)),
                ("chunk_size", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("uploading", "Uploading"),
                            ("complete", "Complete"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "messages_attachment_upload",
                "indexes": [
                    models.Index(fields=["user", "room", "status"], name="att_upl_user_room_st_idx"),
                    models.Index(fields=["expires_at"], name="attachment_upload_exp_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageReadState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_states",
                        to="rooms.room",
                    ),
                ),
                (
                    "last_read_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chat_messages.message",
                    ),
                ),
                ("last_read_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "messages_read_state",
                "indexes": [
                    models.Index(fields=["user", "room"], name="read_state_user_room_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "room"), name="read_state_user_room_uniq"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageReadReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_receipts",
                        to="chat_messages.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_read_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("read_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "messages_read_receipt",
                "indexes": [
                    models.Index(fields=["message", "read_at"], name="read_receipt_msg_read_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("message", "user"), name="read_receipt_message_user_uniq"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="chat_messages.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("emoji", models.CharField(max_length=255, validators=[messages.models.validate_reaction_emoji])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "messages_reaction",
                "indexes": [
                    models.Index(fields=["message"], name="reaction_message_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("message", "user", "emoji"), name="reaction_msg_user_emoji_uniq"),
                ],
            },
        ),
    ]
