# Generated by Django 4.1.13 on 2026-06-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'is_deleted', 'id'], name='msg_room_deleted_id_idx'),
        ),
    ]
