# Generated by Django 4.1.13 on 2026-06-10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Friendship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "friends_friendship",
                "indexes": [
                    models.Index(fields=["to_user", "status"], name="friendship_to_status_idx"),
                    models.Index(fields=["from_user", "status"], name="friendship_from_status_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("from_user", "to_user"), name="friendship_unique_pair"),
                    models.CheckConstraint(
                        check=models.Q(("from_user", models.F("to_user")), _negated=True),
                        name="friendship_no_self",
                    ),
                ],
            },
        ),
    ]
