# Generated by Django 4.1.13 on 2026-06-10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="rooms.room",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(default="#99AAB5", help_text="Hex color code, e.g. #FF0000", max_length=7)),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Higher position = more authority. Used to resolve hierarchy.",
                    ),
                ),
                (
                    "permissions",
                    models.BigIntegerField(default=0, help_text="Bitwise permission mask (see roles.permissions.Perm)."),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, help_text="If True, this is the @everyone role (auto-applied to all members)."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "roles_role",
                "ordering": ["-position"],
                "indexes": [
                    models.Index(fields=["room", "position"], name="role_room_position_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("room", "name"), name="role_room_name_uniq"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="rooms.room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("roles", models.ManyToManyField(blank=True, related_name="members", to="roles.role")),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Per-room display name (like Discord server nickname).",
                        max_length=32,
                    ),
                ),
                ("is_banned", models.BooleanField(default=False)),
                ("ban_reason", models.TextField(blank=True, default="")),
                (
                    "banned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bans_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "muted_until",
                    models.DateTimeField(blank=True, help_text="Muted until this time (null = not muted).", null=True),
                ),
                (
                    "muted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mutes_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "roles_membership",
                "indexes": [
                    models.Index(fields=["user", "room"], name="membership_user_room_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("room", "user"), name="membership_room_user_uniq"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PermissionOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_overrides",
                        to="rooms.room",
                    ),
                ),
                (
                    "target_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="roles.role",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("allow", models.BigIntegerField(default=0)),
                ("deny", models.BigIntegerField(default=0)),
            ],
            options={
                "db_table": "roles_permissionoverride",
                "constraints": [
                    models.CheckConstraint(
                        check=models.Q(("target_role__isnull", False), ("target_user__isnull", False), _connector="OR"),
                        name="override_has_target",
                    ),
                ],
            },
        ),
    ]
