# Generated by Django 4.1.13 on 2026-07-01 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
            ],
            options={
                'verbose_name': 'Участник группы',
                'verbose_name_plural': 'Участники групп',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('roles.membership',),
        ),
        migrations.CreateModel(
            name='GroupRole',
            fields=[
            ],
            options={
                'verbose_name': 'Роль группы',
                'verbose_name_plural': 'Роли групп',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('roles.role',),
        ),
    ]
