# Generated by Django 4.1.13 on 2026-06-10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.avatar_service
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
        ("auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("login", models.CharField(db_index=True, max_length=254, unique=True)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ("email_verified", models.BooleanField(default=False)),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="public_id must be a positive 10-digit numeric value.",
                                regex="^[1-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users_user",
                "indexes": [
                    models.Index(fields=["login"], name="users_user_login_idx"),
                    models.Index(fields=["public_id"], name="users_user_public_id_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("email__isnull", False)),
                        fields=("email",),
                        name="users_user_email_uniq",
                    ),
                ],
            },
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="OAuthIdentity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("google", "Google")], max_length=32)),
                ("provider_user_id", models.CharField(max_length=191)),
                ("email_from_provider", models.EmailField(blank=True, default="", max_length=254)),
                ("name_from_provider", models.CharField(blank=True, default="", max_length=150)),
                ("avatar_url_from_provider", models.URLField(blank=True, default="", max_length=2048)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["provider", "provider_user_id"], name="users_oauth_provider_uid_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_user_id"),
                        name="users_oauth_provider_uid_uniq",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, default="", max_length=150)),
                ("image", models.ImageField(blank=True, upload_to=users.avatar_service.profile_avatar_upload_to)),
                ("avatar_url", models.URLField(blank=True, default="", max_length=2048)),
                ("avatar_crop_x", models.FloatField(blank=True, null=True)),
                ("avatar_crop_y", models.FloatField(blank=True, null=True)),
                ("avatar_crop_width", models.FloatField(blank=True, null=True)),
                ("avatar_crop_height", models.FloatField(blank=True, null=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicHandle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("handle", models.CharField(db_index=True, max_length=30, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_handle",
                        to="rooms.room",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_handle",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecurityRateLimitBucket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope_key", models.CharField(db_index=True, max_length=191, unique=True)),
                ("count", models.PositiveIntegerField(default=0)),
                ("reset_at", models.DateTimeField(db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["reset_at"], name="users_rl_reset_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserTwoFactor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("secret_encrypted", models.TextField(blank=True, default="")),
                ("enabled_at", models.DateTimeField(blank=True, null=True)),
                ("last_accepted_timestep", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["enabled_at"], name="users_2fa_enabled_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="publichandle",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("user__isnull", False), ("room__isnull", True)),
                    models.Q(("user__isnull", True), ("room__isnull", False)),
                    _connector="OR",
                ),
                name="users_public_handle_xor_owner",
            ),
        ),
    ]
