# Generated by Codex on 2026-06-09

from django.db import migrations, models

import users.avatar_service


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_usertwofactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default=users.avatar_service.user_password_default_avatar_path,
                upload_to=users.avatar_service.profile_avatar_upload_to,
            ),
        ),
    ]
